---
all:
  children:
    rpi5:
      hosts:
        claw:
          ansible_host: 10.1.10.220
          ansible_user: picocluster
          ansible_connection: local
    orin:
      hosts:
        crush:
          ansible_host: 10.1.10.221
          ansible_user: picocluster
