---
- name: restart swap
  service:
    name: dphys-swapfile
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart openclaw
  systemd:
    name: openclaw
    state: restarted
